version: "2"
services:
  app:
    environment:
      - MONGODB_URI=mongodb://${DB_USER}:${DB_PASSWORD}@db:27017/elysian
      - RABITMQ_URI=amqp://${MQ_USER}:${MQ_PASSWORD}@mq:5672?heartbeat=2
      - BLOCKCHAIN_URI_REST=https://explorer_uat.ixo.world/api/
      - ETHEREUM_API=https://ropsten.infura.io/
      - ASYM_CYPHER=${ASYMCYPHER}
      - ASYM_KEY=${ASYMKEY}
      - NODEDID=
  db:
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${ROOT}
      - MONGO_INITDB_ROOT_PASSWORD=${ROOTPASS}

  cache:
    ports:
      - "11211:11211"

  mq:
    ports:
      - "5672:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=${MQ_USER}
      - RABBITMQ_DEFAULT_PASS=${MQ_PASSWORD}

  pol:
    environment:
      - RABITMQ_URI=amqp://${MQ_USER}:${MQ_PASSWORD}@mq:5672?heartbeat=2
      - BLOCKCHAIN_URI_SYNC=http://blockchain_uat.ixo.world:46657/broadcast_tx_sync?tx=0x
      - BLOCKCHAIN_URI_COMMIT=http://blockchain_uat.ixo.world:46657/broadcast_tx_commit?tx=0x
      - BLOCKCHAIN_URI_VALIDATE=http://blockchain_uat.ixo.world:46657/tx?hash=0x
      - ETHEREUM_API=https://ropsten.infura.io/

  cli:
    environment:
      - MONGODB_URI=mongodb://${DB_USER}:${DB_PASSWORD}@db:27017/elysian
      - BLOCKCHAIN_URI_REST=https://explorer_uat.ixo.world/api/did/getByDid/